name: Deploy to AWS ECS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.ecr.outputs.registry }}/timeoff-app:latest

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: infra-terraform

    - name: Terraform Apply (auto-approve)
      run: terraform apply -auto-approve
      working-directory: infra-terraform

    - name: Get Task Definition ARN from Terraform Output
      id: tfoutput
      run: |
        echo "task_def_arn=$(terraform -chdir=infra-terraform output -raw task_definition_arn)" >> $GITHUB_OUTPUT

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.tfoutput.outputs.task_def_arn }}
        service: timeoff-service
        cluster: timeoff-cluster
        wait-for-service-stability: true
